[workspace.package]
version = "0.0.3"
authors = ["chevdor <chevdor@gmail.com>", "Wilfried Kopp <wilfried@parity.io>"]
edition = "2021"
homepage = "https://github.com/Chevdor/prdoc"
keywords = ["cli", "documentation", "parity"]
license = "MIT"
repository = "https://github.com/Chevdor/prdoc"

[workspace]
resolver = "2"
members = [
	"cli",
	"prdoclib",
]

[profile.production]
inherits = "release"
lto = true
panic = "abort"
opt-level = "z"
codegen-units = 1
