[workspace.package]
version = "0.0.1"
authors = ["chevdor <chevdor@gmail.com>", "Wilfried Kopp <wilfried@parity.io>"]
edition = "2021"

[workspace]
resolver = "2"
members = [
	"cli",
	"prdoclib",
]

[profile.production]
inherits = "release"
lto = true
panic = "abort"
opt-level = "z"
codegen-units = 1
